# Generated by Django 2.1 on 2018-09-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('lessons', models.ManyToManyField(to='timetable.TimeTable')),
                ('student', models.ManyToManyField(to='students.Student')),
            ],
        ),
    ]
