# Generated by Django 2.1 on 2018-09-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
