# Generated by Django 2.1 on 2018-10-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('timetable', '0003_auto_20180904_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='lessons',
        ),
        migrations.AddField(
            model_name='attendance',
            name='lessons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.TimeTable'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
    ]
